flowchart TB
                N((N))
                N1((N₁))
                N2((N₂))
                M((M))
                N -->|one interaction| N1
                N -->|one interaction| N2
                N1 -->|one interaction| M
                N2 -->|one interaction| M
