flowchart TB
                  Fp["principal"]
                  F@{ shape: triangle, label: "F" }
                  Fa0@{ shape: rect, label: "1st aux" }
                  Fa1@{ shape: rect, label: "2nd aux" }
                  Fp -->|principal| F
                  F --- Fa0
                  F --- Fa1
