flowchart TB
                  tu0["d₀"]
                  tu1["d₁"]
                  tu2["d₂"]
                  tl0["d₀"]
                  tl1["d₁"]
                  tl2["d₂"]
                  tu0 --> tl0
                  tu1 --> tl1
                  tu2 --> tl2
